// This file is auto-generated by @hey-api/openapi-ts

export const $AddressDTO = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        street: {
            type: 'string'
        },
        zip: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        additional: {
            type: 'string'
        },
        po: {
            type: 'string'
        },
        poZip: {
            type: 'string'
        },
        district: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        locality: {
            type: 'string'
        }
    }
} as const;

export const $PersonDTO = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        firstName: {
            type: 'string',
            nullable: true
        },
        allFirstNames: {
            type: 'string',
            nullable: true
        },
        lastName: {
            type: 'string'
        },
        academicTitle: {
            type: 'string',
            nullable: true
        },
        birthDate: {
            type: 'string',
            nullable: true
        },
        addressId: {
            type: 'integer',
            format: 'int32'
        },
        familyId: {
            type: 'integer',
            format: 'int32'
        },
        familyRole: {
            type: 'string'
        },
        gender: {
            type: 'string'
        },
        placeOfBirth: {
            type: 'string'
        },
        nationality: {
            type: 'string'
        },
        countryOfOrigin: {
            type: 'string'
        },
        religion: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        salutation: {
            type: 'string'
        },
        prefix: {
            type: 'string'
        }
    }
} as const;

export const $CreatePersonDTO = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        firstName: {
            type: 'string',
            nullable: true
        },
        allFirstNames: {
            type: 'string',
            nullable: true
        },
        lastName: {
            type: 'string'
        },
        academicTitle: {
            type: 'string',
            nullable: true
        },
        birthDate: {
            type: 'string',
            nullable: true
        },
        addressId: {
            type: 'integer',
            format: 'int32'
        },
        familyId: {
            type: 'integer',
            format: 'int32'
        },
        familyRole: {
            type: 'string'
        },
        gender: {
            type: 'string'
        },
        placeOfBirth: {
            type: 'string'
        },
        nationality: {
            type: 'string'
        },
        countryOfOrigin: {
            type: 'string'
        },
        religion: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        salutation: {
            type: 'string'
        },
        prefix: {
            type: 'string'
        },
        mobilePhone: {
            type: 'string'
        },
        householdPhone: {
            type: 'string'
        },
        businessPhone: {
            type: 'string'
        },
        street: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        zipCode: {
            type: 'string'
        },
        city: {
            type: 'string'
        }
    }
} as const;

export const $SuccessResponse = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const $ReligionDTO = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    }
} as const;

export const $DistrictDTO = {
    required: ['name'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    }
} as const;

export const $CreateAddressDTO = {
    type: 'object',
    properties: {
        personId: {
            type: 'integer',
            format: 'int32'
        },
        street: {
            type: 'string'
        },
        zip: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        additional: {
            type: 'string'
        },
        po: {
            type: 'string'
        },
        poZip: {
            type: 'string'
        },
        district: {
            type: 'string'
        },
        country: {
            type: 'string'
        }
    }
} as const;

export const $GroupDTO = {
    required: ['id', 'name', 'type'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        grade: {
            type: 'string'
        },
        character: {
            type: 'string'
        },
        schoolYear: {
            type: 'string'
        }
    }
} as const;

export const $CountryDTO = {
    required: ['iso', 'name'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        iso: {
            type: 'string'
        }
    }
} as const;

export const $RelationshipDTO = {
    type: 'object',
    properties: {
        personId: {
            type: 'integer',
            format: 'int32'
        },
        relationshipType: {
            type: 'string'
        },
        physical: {
            type: 'boolean'
        },
        custody: {
            type: 'boolean'
        },
        realParent: {
            type: 'boolean'
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const $GroupMembershipDTO = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        entry: {
            type: 'string'
        },
        exit: {
            type: 'string'
        }
    }
} as const;