export const mockMembers = [
    {
        id: 6495,
        firstName: 'Jennifer',
        lastName: 'Robinson',
        allFirstNames: null,
        academicTitle: null,
        prefix: null,
        salutation: null,
        addressId: null,
        familyRole: null,
        gender: null,
        email: null,
        religion: 'Christianity',
        birthDate: '1979-09-16',
        placeOfBirth: null,
        nationality: 'DJ',
        address: null,
    },
    {
        id: 8434,
        firstName: 'Andrew',
        lastName: 'Reese',
        allFirstNames: null,
        academicTitle: null,
        prefix: null,
        salutation: null,
        addressId: 989,
        familyRole: 'Mother',
        gender: null,
        email: null,
        religion: null,
        birthDate: '1968-11-17',
        placeOfBirth: null,
        nationality: 'IE',
        address: {
            id: 538,
            street: '84812 Lee Courts',
            zip: null,
            city: null,
            country: 'Hong Kong',
            locality: null,
            district: 'South Carolina',
        },
    },
    {
        id: 4337,
        firstName: null,
        lastName: 'Kelly',
        allFirstNames: 'Amy',
        academicTitle: null,
        prefix: 'Mr.',
        salutation: 'Dear',
        addressId: 755,
        familyRole: 'Child',
        gender: 'other',
        email: null,
        religion: null,
        birthDate: '1988-02-02',
        placeOfBirth: 'East Jason',
        nationality: null,
        address: {
            id: 712,
            street: '8448 Garza Wells Suite 590',
            zip: '90023',
            city: 'Paulland',
            country: null,
            locality: null,
            district: null,
        },
    },
    {
        id: 5193,
        firstName: null,
        lastName: 'Rose',
        allFirstNames: null,
        academicTitle: 'Dr.',
        prefix: null,
        salutation: 'Dear',
        addressId: 84,
        familyRole: null,
        gender: 'female',
        email: null,
        religion: 'Islam',
        birthDate: '1956-05-09',
        placeOfBirth: 'West John',
        nationality: 'NA',
        address: null,
    },
    {
        id: 9261,
        firstName: 'Thomas',
        lastName: 'May',
        allFirstNames: null,
        academicTitle: 'Dr.',
        prefix: 'Mrs.',
        salutation: 'Hello',
        addressId: 376,
        familyRole: 'Father',
        gender: 'female',
        email: null,
        religion: null,
        birthDate: '1953-10-19',
        placeOfBirth: 'Reginaland',
        nationality: 'TW',
        address: null,
    },
];


export const mockRelationships = [
    {
        "personId": 1,
        "relationshipType": "daughter",
        "custody": true,
        "realParent": true,
        "physical": true,
        "notes": null
    },
    {
        "personId": 2,
        "relationshipType": "son",
        "custody": true,
        "realParent": true,
        "physical": true,
        "notes": null
    }
]
